name: Build and Push

on:
  pull_request:
  push:
    branches:
      - main
      - release/*
    tags: '*'
  release:
    types:
      - created

env:
  SWIFT_VERSION: 5.8
  SWIFTLINT_VERSION: 0.51.0

jobs:
  buildx:
    name: Build and Push the Docker Images
    runs-on: ubuntu-latest    
    steps:
      - name: Compute Tag
        uses: actions/github-script@v6
        id: compute-tag
        with:
          result-encoding: string
          script: |
            if (context.eventName === "pull_request") {
              return "pr-" + context.issue.number;
            }
            if (context.eventName === "push") {
              if (context.ref.startsWith("refs/tags/")) {
                return context.ref.slice(10);
              }
              if (context.ref === "refs/heads/main") {
                return "latest";
              }
            }
            return "FALSE";
      
      - uses: actions/checkout@v3

      - name: Docker Login
        id: docker-login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest

      - name: Build Image and Push to GitHub Container Registry and DockerHub
        uses: docker/build-push-action@v4
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
        with:
          context: .
          build-args: |
            "BUILDER_IMAGE=swift:${{ env.SWIFT_VERSION }}-focal"
            "RUNTIME_IMAGE=swift:${{ env.SWIFT_VERSION }}-focal"
            "SWIFTLINT_VERSION=${{ env.SWIFTLINT_VERSION }}"
          tags: |
            ls1tum/artemis-swift-swiftlint-docker:swift${{ env.SWIFT_VERSION }}
            ls1tum/artemis-swift-swiftlint-docker:swiftlint${{ env.SWIFTLINT_VERSION }}
            ls1tum/artemis-swift-swiftlint-docker:${{ steps.compute-tag.outputs.result }}
            ghcr.io/ls1intum/artemis-swift-swiftlint-docker:swift${{ env.SWIFT_VERSION }}
            ghcr.io/ls1intum/artemis-swift-swiftlint-docker:swiftlint${{ env.SWIFTLINT_VERSION }}
            ghcr.io/ls1intum/artemis-swift-swiftlint-docker:${{ steps.compute-tag.outputs.result }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}

